apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  generation: 10
  name: flamingo-vcluster
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: username
        value: flamingo-vcluster
      - name: hostname
        value: gartner.opsmx.net
    path: vcluster-argocd-chart
    repoURL: https://github.com/gopaljayanthi/vcluster-helm
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
