apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.username }}-argo-kubectl-vcluster
spec:
  template:
    spec:
      containers:
      - name: argo-kubectl-vcluster
        command: ["/script/vcluster-create.sh"]
        args:
        - {{ .Values.username }}
        env:
        - name: argocdhost
          value: {{ .Values.argocdhostname }}  # Please update the Argocd Ingress Value
        image: quay.io/opsmxpublic/argo-kubectl-vcluster:wyq
        volumeMounts:
        - mountPath: /argocd
          name: argocd
        - mountPath: /script
          name: script
        - mountPath: /values
          name: values
      serviceAccountName: argocd-application-controller
      volumes:
      - name: values
        configMap:
          name: vcluster-values-yaml
          items:
          - key: "values.yaml"
            path: "values.yaml"
      - name: argocd
        secret:
          secretName: argocd-initial-admin-secret
      - name: script
        configMap:
          name: vcluster-create-script
          defaultMode: 0744
          items:
          - key: "vcluster-create.sh"
            path: "vcluster-create.sh"
      restartPolicy: Never
  backoffLimit: 4
