apiVersion: batch/v1
kind: Job
metadata:
  name: argo-kubectl-vcluster
spec:
  template:
    spec:
      containers:
      - name: argo-kubectl-vcluster
        command: ["/script/vcluster-create.sh"]
        args:
        - {{ .Values.username }}        # Please update the username
        env:
        - name: argocdhost
          value: {{ .Values.argocdhostname }}  # Please update the Argocd Ingress Value
        image: quay.io/opsmxpublic/argo-kubectl-vcluster:v1
        volumeMounts:
        - mountPath: /argocd
          name: argocd
        - mountPath: /init
          name: init
        - mountPath: /script
          name: script
      serviceAccountName: argocd-application-controller
      volumes:
      - name: argocd
        secret:
          secretName: argocd-initial-admin-secret
      - name: init
        configMap:
          name: init-vcluster
          items:
          - key: "init-vcluster.yaml"
            path: "init-vcluster.yaml"
      - name: script
        configMap:
          name: vcluster-create-script
          defaultMode: 0744
          items:
          - key: "vcluster-create.sh"
            path: "vcluster-create.sh"
      restartPolicy: Never
  backoffLimit: 4
